Implement Basic ManageBac Overview and CAS screens
SardonyxApp/sardonyx pull request #4
Opened 2019-01-26 11:37 UTC by FoxInFlame

This pull request will add screens for Overview and CAS inside the Managebac tab of Sardonyx.
Some additional screens to accommodate those two screens may be added, such as detail screens for each CAS experience.

More sophistication will be brought to these screens in later pull requests.

2019-03-16 04:31 UTC, natsuozawa commented on .gitignore
> +.env
It doesn't look like .env and .env.production are correctly ignored...

2019-03-16 04:47 UTC, natsuozawa commented on src/components/CalendarDate.js
> +              {this.shortMonthNames[this.props.date.getMonth()]}
You may want to use 

```js
new Intl.DateTimeFormat('en-US', { month: 'short'}).format(this.props.date);
```

2019-03-16 07:04 UTC, natsuozawa requested changes
Please make sure the app is stable before you merge

2019-03-16 07:04 UTC, natsuozawa commented on src/components/ExpandableCard.js
> +
Remove empty properties?

2019-03-16 07:04 UTC, natsuozawa commented on src/components/CalendarDate.js
> +              {this.shortMonthNames[this.props.date.getMonth()]}
You may want to use 

```js
new Intl.DateTimeFormat('en-US', { month: 'short'}).format(this.props.date);
```

2019-03-16 07:04 UTC, natsuozawa commented on .gitignore
> +.env
.env is not correctly ignored?

2019-03-16 07:04 UTC, natsuozawa commented on src/components/ExtendedDeadline.js
> +        });
Error handling please 
(Promise rejection)

2019-03-16 07:04 UTC, natsuozawa commented on src/components/UpcomingExpandableCard.js
> +    this._navigateToUpcomingEventScreen = this._navigateToUpcomingEventScreen.bind(
One line is fine here 
```js
this._navigateToUpcomingEventScreen = this._navigateToUpcomingEventScreen.bind(this);
```

2019-03-16 07:04 UTC, natsuozawa commented on src/styles.js
> +};
This is unsustainable. Let's parse the color server side and pass it along with the other label data.

2019-03-16 07:04 UTC, natsuozawa commented on src/screens/LoginScreen.js
>            })}
The styling seems a bit broken here and the checkbox is ugly (the font doesn't match, etc)

I don't think we need a checkbox, just include a statement that says 
"By signing in, you agree to our Terms of Service and Privacy Policy"

Link to `BASE_URL + '/terms'` and `BASE_URL + '/privacy'`

2019-03-16 07:04 UTC, natsuozawa commented on src/components/ExtendedDeadline.js
> +  FlatList
FlatList is not used

2019-03-18 13:29 UTC, natsuozawa approved these changes

2019-03-18 13:29 UTC, natsuozawa commented on src/screens/LoginScreen.js
>            })}
We will work on this later.

2019-03-26 23:04 UTC, FoxInFlame commented on src/screens/LoginScreen.js
>            })}
Understood.

2019-03-26 23:04 UTC, FoxInFlame commented on src/styles.js
> +};
Understood.

2019-03-26 23:04 UTC, FoxInFlame commented on src/components/UpcomingExpandableCard.js
> +    this._navigateToUpcomingEventScreen = this._navigateToUpcomingEventScreen.bind(
Fixed.

2019-03-26 23:05 UTC, merged